export const deliveryPipeline = [
  {
    step: "01",
    title: "Architecture",
    evidence: "38 entity sets · 18 migrations",
    description: "Domain modeling and EF Core migrations establish maintainable boundaries before interface work begins.",
    project: "TapMood",
  },
  {
    step: "02",
    title: "Interface",
    evidence: "15+ role-aware screens",
    description: "Responsive product flows carry a shared design language across student, teacher, and administrator roles.",
    project: "VNCaps",
  },
  {
    step: "03",
    title: "API & Data",
    evidence: "117 endpoint mappings",
    description: "REST and real-time contracts connect client behavior to application logic, persistence, and background work.",
    project: "TapMood",
  },
  {
    step: "04",
    title: "Quality",
    evidence: "92 automated tests",
    description: "Application and API coverage protect critical workflows before a release reaches production.",
    project: "TapMood",
  },
  {
    step: "05",
    title: "Deployment",
    evidence: "Docker · Render · hosted workers",
    description: "Containerized services and hosted background workers complete the path from repository to production.",
    project: "TapMood · HabiStride",
  },
] as const;

export const technologyMarquee = [
  "Flutter",
  "React",
  "Next.js",
  "TypeScript",
  "Tailwind CSS",
  "shadcn/ui",
  "Ant Design",
  "MUI",
  "React Native",
  "Expo",
  "NestJS",
  "ASP.NET Core",
  "Laravel",
  "Strapi",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Firebase",
  "SignalR",
  "Socket.IO",
  "REST API",
  "Zustand",
  "React Query",
  "Docker",
  "Render",
  "Cloudinary",
  "FFmpeg",
  "Git",
  "Figma",
  "Framer Motion",
] as const;
