export const deliveryPipeline = [
  {
    step: "01",
    title: "Architecture",
    evidence: "35 SQLAlchemy models",
    description: "Learning, research, authentication, privacy, and entitlement models establish the foundation for an AI learning product.",
    project: "Bravodemy",
  },
  {
    step: "02",
    title: "Interface",
    evidence: "15+ role-aware screens",
    description: "Responsive product flows carry a shared design language across student, teacher, and administrator roles.",
    project: "VNCaps",
  },
  {
    step: "03",
    title: "API & Data",
    evidence: "107 FastAPI endpoints · AI research",
    description: "Source-grounded generation connects Gemini, Exa, and Tavily research to learning workflows, with Langfuse tracing.",
    project: "Bravodemy",
  },
  {
    step: "04",
    title: "Quality",
    evidence: "192 backend · 151 frontend tests",
    description: "85.11% backend coverage plus accessibility and responsive CI journeys protect delivery across three browser engines.",
    project: "Bravodemy",
  },
  {
    step: "05",
    title: "Deployment",
    evidence: "Render · Neon · GitHub Actions",
    description: "Independent UI/API services use health-gated auto-deploys, pooled runtime connections, and direct migration connections.",
    project: "Bravodemy",
  },
] as const;

export const technologyMarquee = [
  "Python",
  "FastAPI",
  "SQLAlchemy",
  "Gemini",
  "Exa",
  "Tavily",
  "Langfuse",
  "Neon",
  "GitHub Actions",
  "Pytest",
  "Vitest",
  "Playwright",
  "GSAP",
  "Flutter",
  "React",
  "Next.js",
  "TypeScript",
  "Tailwind CSS",
  "shadcn/ui",
  "Ant Design",
  "MUI",
  "React Native",
  "Expo",
  "NestJS",
  "ASP.NET Core",
  "Laravel",
  "Strapi",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Firebase",
  "SignalR",
  "Socket.IO",
  "REST API",
  "Zustand",
  "React Query",
  "Docker",
  "Render",
  "Cloudinary",
  "FFmpeg",
  "Git",
  "Figma",
  "Framer Motion",
] as const;
